// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CartController from "./cart_controller"
application.register("cart", CartController)

import CategoryFilterController from "./category_filter_controller"
application.register("category-filter", CategoryFilterController)

import DashboardController from "./dashboard_controller"
application.register("dashboard", DashboardController)

import FilterdateController from "./filterdate_controller"
application.register("filterdate", FilterdateController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProductsController from "./products_controller"
application.register("products", ProductsController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)
